### 矩阵的数量乘法
矩阵直接和常量相乘，矩阵每个位置进行相乘即可；

In [3]:
import numpy as np
A = np.array([[1, 2, 3],
              [4, 5, 6]])
print(A*2)

[[ 2  4  6]
 [ 8 10 12]]


### 矩阵与矩阵的乘法
仔细观察这个计算公式，我们总结出以下的一些要求和规律：<BR>
1.左边矩阵的列数要和右边矩阵的行数相等 <BR>
2.左边矩阵的行数决定了结果矩阵的行数 <BR>
3 右边矩阵的列数决定了结果矩阵的列数<BR>

In [4]:
import numpy as np
A = np.array([[1, 2],
              [3, 4],
              [5, 6]])
x = np.array([[4, 5]]).T

print(np.dot(A, x))
print(np.matmul(A,x))

[[14]
 [32]
 [50]]
[[14]
 [32]
 [50]]


### 矩阵与向量的乘法
1.向量可以在外面增加一维数据，例如：[2,3] -> [[2,3]] 转变为 1行2列

In [21]:
import torch
A = torch.rand(size=(3,2))
B = torch.rand(size=(2,4))
a = torch.linspace(0,1,2)
print(a)
# print(torch.mul(A,B.T))
print(torch.matmul(A,B))
# print(np.matmul(A,x))

tensor([0., 1.])
tensor([[0.0871, 0.5428, 0.3972, 0.3544],
        [0.1492, 0.4471, 0.5002, 0.5413],
        [0.1070, 0.6887, 0.4961, 0.4382]])
