### pytorch 乘法运算汇总与解析
https://www.jianshu.com/p/de4b6f67051f  
具体详见连接

### 元素相乘
该操作又称作 "哈达玛积", 简单来说就是 tensor 元素逐个相乘。这个操作，是通过 * 也就是常规的乘号操作符定义的操作结果。torch.mul 是等价的。

In [1]:
import torch

# mul 和 * 一致，按照元素位置进行相乘，不做降维
def element_by_element():
    
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([4, 5, 6])
    
    return x * y, torch.mul(x, y)

element_by_element()

(tensor([ 4, 10, 18]), tensor([ 4, 10, 18]))

In [5]:
import torch
# 向量和标量相乘，会进行broadcast进行广播
def element_by_element_broadcast():    
    x = torch.tensor([1, 2, 3])
    y = 2
    return x * y

element_by_element_broadcast()

tensor([2, 4, 6])

### 向量点乘
torch.matmul: If both tensors are 1-dimensional, the dot product (scalar) is returned.
<BR/>如果都是1维的，返回的就是 dot product 结果


In [3]:
import torch
# 向量matmul 点积按照维度相乘之后再相加，会进行降维处理
def vec_dot_product():
    
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([4, 5, 6])
    
    return torch.matmul(x, y)
vec_dot_product()
# tensor(32)

tensor(32)

### 矩阵乘法
torch.matmul: If both arguments are 2-dimensional, the matrix-matrix product is returned.
<BR/>如果都是2维，那么就是矩阵乘法的结果返回。与 torch.mm 是等价的，torch.mm 仅仅能处理的是矩阵乘法。
<BR/>
![avatar](./img/numpy.dot.png)  
![avatar](./img/matmul.jpg)   
<font color=yellow>
第一个matrix的行（一维）决定输出单元格的行数（一维）  
第二个matrix的列（二维）决定了输出单元格列数（二维）   
第一个矩阵：列决定行，第二矩阵：行决定列，行列相乘再相加
</font>

如果是二维数组（矩阵）之间的运算，则得到的是矩阵积（mastrix product）。
所得到的数组中的每个元素为，第一个矩阵中与该元素行号相同的元素与第二个矩阵与该元素列号相同的元素，两两相乘后再求和。
这句话有点难理解，但是这句话里面没有哪个字是多余的。结合下图理解这句话。
<BR>
mm 只能使用在二维矩阵 matmul可以使用多为矩阵相乘

<br/>
解释：
    x = torch.tensor([
        [1, 1, 1],
        [1, 1, 1]
    ])
    y = torch.tensor([
        [2, 2],
        [2, 2],
        [2, 3]
    ])
<br/>
x 先使用第1行和 y 的第1列相乘，得到新matrix [Update,0][0,0]数据，和y相乘的列决定了当前列的位置，即为0 
<br/>
x 先使用第1行和 y 的第2列相乘，得到新matrix [0,Update][0,0]数据，和y相乘的列决定了当前列的位置，即为1
<br/>

In [5]:
import torch

# tensor([[1, 2, 3],
#         [4, 5, 6]])
# y = torch.tensor([
#      [7, 8],
#      [9, 10],
#      [11, 12]
# ])

# 理解1，如上图
# x = (a,b) 
# y = (b,c) 
# x * y= (a,c)
# 计算过程：
# a[0] = 1*7 + 2*9 + 3*11 = 58
# a[1] = 1*8 + 2*10 + 3*12 = 64


# 理解2
# x = (2,3) (a,b)
# y = (3,2) (c,d)
# y = y.transpose(0,1) -> (2,3)
# x * y = (a*c,a*d),(b*c,b*d) 行之间进行乘法和加法求和



def matrix_multiple():
    
    x = torch.tensor([
        [1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [6, 7, 8]
    ])
    print(x)
    
    y = torch.tensor([
        [1, 2,3],
        [4, 5,6],
        [7, 8,9]
    ])
    # print(y)
    print(y.T)
    # 转置之后 是通过

    
    return torch.matmul(x, y), torch.mm(x, y)

matrix_multiple()

tensor([[1, 2, 3],
        [4, 5, 6],
        [4, 5, 6],
        [6, 7, 8]])
tensor([[1, 4, 7],
        [2, 5, 8],
        [3, 6, 9]])


(tensor([[ 30,  36,  42],
         [ 66,  81,  96],
         [ 66,  81,  96],
         [ 90, 111, 132]]),
 tensor([[ 30,  36,  42],
         [ 66,  81,  96],
         [ 66,  81,  96],
         [ 90, 111, 132]]))

### vector 与 matrix 相乘
torch.matmul: If the first argument is 1-dimensional and the second argument is 2-dimensional, a 1 is prepended to its dimension for the purpose of the matrix multiply. After the matrix multiply, the prepended dimension is removed.

如果第一个是 vector, 第二个是 matrix, 会在 vector 中增加一个维度。也就是 vector 变成了  与 matrix  相乘之后，变成 , 在结果中将  维 再去掉。

<font color=yellow>
vector 与 matrix 相乘 
vector 增加第一维度，后续按照标准规则进行
</font>


In [6]:
import torch
# (1,3) * (3,2) = (1,2)
# 但是matmul(x,y)不能进行位置互换，需要满足 行列相同原则

# torch.matmul(a, b)
# a 决定输出行 b 决定输出列

def vec_matrix():
    x = torch.tensor([1, 2, 3])
    y = torch.tensor([
        [7, 8, 1],
        [9, 10, 1],
        [11, 12, 1]
    ])

# operation process:
# 7 + 18 + 33 = 58
# 8 + 20 + 36 = 64
    
    return torch.matmul(x, y)

vec_matrix()
# tensor([58, 64,  6])

tensor([58, 64,  6])

### matrix 与 vector 相乘
同样的道理， vector会被扩充一个维度。  
<font color=yellow>
matrix 与 vector 相乘
vector 增加第二维度，满足 行列相同原则，之后进行行列相同累计；   
</font>
<font color=yellow>
如果需要matrix降维，可以乘一个向量   
</font>

In [1]:
import torch

# matrix 和 vector不相同
def matrix_vec_unmatch():
    x = torch.tensor([
        [1, 2, 3],
        [4, 5, 6]
    ])
    
    y = torch.tensor([
        7, 8, 9
    ])

    # 计算过程
    # 将y空充维度[3] -> [3,1]:[[[[7,8,9]]]]???
    
    # 1*7 + 2*8 + 3*9 = 50
    # 4*7 + 5*8 + 3*9 = 122
    return torch.matmul(x, y)

matrix_vec_unmatch()
# tensor([ 50, 122])


# 1.将y进行填充变成:y=[[7],[8]]，因为需要保持和x的二维大小相同，此时 y.shape = (3,1)
# 2. 进行行列相乘，相加，即：
#    1*10 + 2*11 = 32
#    3*10 + 4*11 = 74
#    5*10 + 6*11 = 116
#    7*10 + 8*11 = 158
# 生成数组[[32],[74],[116],[158]] = (4,1)，再去掉维度即[4]
# 第一矩阵决定行，第二矩阵决定列的定义没有变化，只是进行维度扩充结算，之后再结果中进行了缩减；
def matrix_vec_match():
    x = torch.tensor([
        [1, 2],
        [3, 4],
        [5, 6],
        [7, 8]
    ])
    
    y = torch.tensor([
        10, 11
    ])
    
    # 1*7 + 2*8 = 23
    # 4*7 + 5*8 = 68
    return torch.matmul(x,y)
    # tensor([ 44,  86, 128, 170])

# print(matrix_vec_match())
# tensor([ 32,  74, 116, 158])

x = torch.tensor([
    [1, 2],
    [3, 4],
    [5, 6],
    [7, 8]
])

y = torch.tensor([
    10, 11
])
print(y.T)

y_1 = torch.tensor([
    10, 11
])

# print(x @ y)
# print(x * y_1)




tensor([ 32,  74, 116, 158])
tensor([10, 11])
tensor([ 32,  74, 116, 158])
tensor([[10, 22],
        [30, 44],
        [50, 66],
        [70, 88]])
